name: Update Version References

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract version
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(git describe --tags --abbrev=0)
          fi
          VERSION_NUM=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version_num=$VERSION_NUM" >> $GITHUB_OUTPUT
          
      - name: Update website version
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          # Update version display
          sed -i "s/Latest version: v[0-9.]\+/Latest version: $VERSION/g" docs/index.html || true
          # Update download links
          sed -i "s/dotfiles-plus\/archive\/refs\/tags\/v[0-9.]\+/dotfiles-plus\/archive\/refs\/tags\/$VERSION/g" docs/index.html || true
          
      - name: Update Homebrew formula
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          VERSION_NUM="${{ steps.version.outputs.version_num }}"
          
          # Download tarball and calculate SHA256
          SHA256=$(curl -sL "https://github.com/anivar/dotfiles-plus/archive/refs/tags/$VERSION.tar.gz" | shasum -a 256 | cut -d' ' -f1)
          
          # Update formula version and SHA
          sed -i "s/version \"[0-9.]\+\"/version \"$VERSION_NUM\"/g" homebrew/dotfiles-plus.rb
          sed -i "s/tags\/v[0-9.]\+\.tar\.gz/tags\/$VERSION.tar.gz/g" homebrew/dotfiles-plus.rb
          sed -i "s/sha256 \"[a-f0-9]\{64\}\"/sha256 \"$SHA256\"/g" homebrew/dotfiles-plus.rb
          
      - name: Update VERSION file
        run: |
          echo "${{ steps.version.outputs.version_num }}" > VERSION
          
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update version references to ${{ steps.version.outputs.version }}

            - Update website version display
            - Update Homebrew formula
            - Update VERSION file
            
            [skip ci]"
            git push origin main
          fi