name: Update Homebrew SHA256

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v2.0.2)'
        required: true
        type: string

jobs:
  update-homebrew-sha:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Determine tag
        id: get_tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "TAG=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Download release and calculate SHA256
        id: calculate_sha
        run: |
          TAG="${{ steps.get_tag.outputs.TAG }}"
          URL="https://github.com/${{ github.repository }}/archive/refs/tags/${TAG}.tar.gz"
          
          echo "Downloading release from: $URL"
          curl -sL "$URL" -o release.tar.gz
          
          SHA256=$(shasum -a 256 release.tar.gz | awk '{print $1}')
          echo "SHA256=${SHA256}" >> $GITHUB_OUTPUT
          echo "Calculated SHA256: $SHA256"
      
      - name: Update Formula
        run: |
          TAG="${{ steps.get_tag.outputs.TAG }}"
          SHA256="${{ steps.calculate_sha.outputs.SHA256 }}"
          VERSION="${TAG#v}"
          
          # Update SHA256 in formula
          sed -i "s/sha256 \"[^\"]*\"/sha256 \"$SHA256\"/" homebrew/dotfiles-plus.rb
          
          # Ensure version and URL are correct
          sed -i "s/version \"[^\"]*\"/version \"$VERSION\"/" homebrew/dotfiles-plus.rb
          sed -i "s|/v[0-9]\+\.[0-9]\+\.[0-9]\+\.tar\.gz|/${TAG}.tar.gz|" homebrew/dotfiles-plus.rb
          
          echo "Updated homebrew/dotfiles-plus.rb with SHA256: $SHA256"
      
      - name: Commit and push changes
        run: |
          TAG="${{ steps.get_tag.outputs.TAG }}"
          git add homebrew/dotfiles-plus.rb
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update Homebrew formula SHA256 for ${TAG}"
            git push origin main
          fi
      
      - name: Create summary
        run: |
          TAG="${{ steps.get_tag.outputs.TAG }}"
          SHA256="${{ steps.calculate_sha.outputs.SHA256 }}"
          
          echo "## ✅ Homebrew Formula Updated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Tag**: ${TAG}" >> $GITHUB_STEP_SUMMARY
          echo "- **SHA256**: \`${SHA256}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **File**: homebrew/dotfiles-plus.rb" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🧪 Test Installation" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "# Direct install from formula" >> $GITHUB_STEP_SUMMARY
          echo "brew install --HEAD https://raw.githubusercontent.com/${{ github.repository }}/main/homebrew/dotfiles-plus.rb" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY